### ISSUE TITLE
Use the word "breath" in timers for Chromaggus' breaths

### ISSUE THREAD

**Issue by SuperNerdEric** [DeadlyBossMods/DBM-Classic#107]
Chromaggus has 5 different breath attacks named "Incinerate", "Corrosive Acid", "Frost Burn", "Ignite Flesh", and "Time Lapse". If the timers included the word breath I think it would make it clearer what they were referring to i.e "Breath: Incinerate". 

I've had multiple instances of raid members getting confused after we tell them to LoS every breath and the timer doesn't say the word breath in it.

The first 2 breath timers already say the word "breath" because they do not know what it will be. I think it would be more consistent for all of them to include the word "breath".

**Comment by MysticalOS** [comment]
in many cases, the timer would truncate if it had breath AND breath name in it. it'd more likely look like this for many "Breath: Inciner..." . I try to avoid timer truncating if I can help it because they are harder to read.

people will figure it out after a couple pulls. It's not like the boss has many abilities.
