### ISSUE TITLE
Can't Move Groups in Combat

### ISSUE THREAD

**Issue by kayti-wow** [DeadlyBossMods/DBM-Classic#11]
Using DBM version 1.13.7 in Wow Classic, I am unable to move players between groups in a raid while in combat.

The errors relate to DBM-Core attempting to call protected functions on the Blizzard raid frames, such as:

```
Date: 2019-09-14 13:09:43
ID: -1
Error occured in: AddOn: DBM-Core
Count: 1
Message: Note: AddOn DBM-Core attempted to call a protected function (SetRaidSubgroup()) during combat lockdown.
Debug:
   [C]: SetRaidSubgroup()
   Blizzard_RaidUI\Blizzard_RaidUI.lua:636: RaidGroupButton_OnDragStop()
   [string "*:OnDragStop"]:5:
      [string "*:OnDragStop"]:1
Locals:
None
AddOns:
  DBMCore, v1.13.7
  DBMDefaultSkin, v
  DBMGUI, v
  DBMStatusBarTimers, v
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=3c7)
```

**Comment by MysticalOS** [comment]
DBM doesn't even call that function, anywhere. You'd probably need a more thorough taintlog to see where taint started, because one it starts it spreads like a virus and any addon can be blamed after that.

**Comment by kayti-wow** [comment]
Sure, but once I disable DBM the issue goes away.

**Comment by Developaws** [comment]
Can you run `/console taintLog 1`, get this error to throw and then send us your "Logs/taint.log" file :)

**Comment by MysticalOS** [comment]
Right, but way taint works is annoying. lets say Mod A taints some variable or execution path. Lets say for example UIDropDown, but that in itself doesn't cause issues, at least until say Mod B also accesses that path in another place, now Mod B didn't cause the taint, but it spread it to a place mod A didn't, by accesses same tainted execution.

I'm not saying completely that dbm isn't at fault, but that's why we need a taint log, to be sure it's not starting somewhere else

**Comment by MysticalOS** [comment]
I do have two questions though

Are you playing horde?
Do you have the "enable retail shaman class colors" enabled?

**Comment by kayti-wow** [comment]
Yes! That's what it was.  With the shaman class colours option disabled it works correctly.

Here's the taintlog:
[taint.log](https://github.com/DeadlyBossMods/DBM-Classic/files/3613012/taint.log)

**Comment by MysticalOS** [comment]
Ok, I need to work on shaman colors a bit more. what's annoying is I try to import a local reference of class colors before modifying them, but it doesn't matter, my write to shaman class colors still spreads to the global. I need to do better with it

**Comment by MysticalOS** [comment]
There was no solution to be found that'd allow changing it globally. Changing it locally woudn't be hard but it'd mean the shaman would be blue in DBM but still pink all over base UI, this is not a solution that makes sense to me, because it's either all or nothing. Mismatching doiesn't work for me, so feature itself had to be scrapped. Removal of feature closes this issue.
