### ISSUE TITLE
AQ40 Ouro's Submerge

### ISSUE THREAD

**Issue by sotheray** [DeadlyBossMods/DBM-Classic#445]
Hi there!
I noticed that in today's changelog you mentioned that the submerge happens randomly. I do not think so:(

The submerge seems to happen when either

Condition 1: 3 minutes after its "birth" (or 3 minutes after we get into combat)
Specificlly, see https://classic.warcraftlogs.com/reports/qY4dQtCZ9yxN6FVm#fight=57&type=casts&view=events&hostility=1
ouro (the second one in the log) casts birth at 02:04 and submerge at 05:05.
This log obeys this condition twice:
https://classic.warcraftlogs.com/reports/qCPAxwkT964VMnZB#fight=2&type=casts&view=events&hostility=1
I find a lot of logs that ouro submerge at 3 minutes (mainly ~03:05) so it may not be just a coincidence.
https://classic.warcraftlogs.com/reports/W74AZpwvCKXdfk83#fight=13
https://classic.warcraftlogs.com/reports/M7yY23Zx1XmHqvjf#fight=57
https://classic.warcraftlogs.com/reports/grpcQ7M3V2ZPKfav#fight=7
https://classic.warcraftlogs.com/reports/wFGrVcmXL9Wzy2Tv#fight=2
https://classic.warcraftlogs.com/reports/yJPNhYjMF2ptwVAB#fight=13
https://classic.warcraftlogs.com/reports/wDb2kRzKHv1x3Ynt#fight=121

Condition 2: no one is in its meele range(?) for several seconds
Mainly happens after ouro casts sweep
or RL asks to run away based on previous experience at private server (see a 9minates fight where ouro seems to submerge randomly: https://classic.warcraftlogs.com/reports/g3DVXT2jJm7x9wWA#fight=57)
The submerge that do not happen at 3min usually obeys this rule (you may check the fight replay).

p.s. There are still some logs that I cannot explain, like this: (based on the replay) https://classic.warcraftlogs.com/reports/d8tCHzav2RhkFVNP#fight=58
But I do think a 3 minutes timer of submerge in this fight exists.

**Comment by MysticalOS** [comment]
I looked at so many logs that I could not explain timers. I'm open to investigating it though but I saw times spanning 1 minute to 3 minutes from engage. and then the time between submerges in the super long pulls that saw 2, was also variable and iffy.

if it's a 3 minute timer with an odd no melee condition though that might explain a lot of random times. I think that's part that needs figuring out, if we could figure out what makes the timers Look random, but not actually be random, we can possibly get a timer added, but it may also hinge on condition community actually understands that just because timer says one thing, doesn't mean he won't still submerge if the other condition happens.

**Comment by sotheray** [comment]
Thanks for your reply:)
I think Ouro is very similar to Ragnaros if my guess holds, with the same 3min submerge timer and a no melee condition (or Ragnaros will start to kill ranged players).

Of course simply add a timer may cause misunderstanding if there is other condition, maybe a timer called “sure to submerge” is ok? haha

I cannot say if my guess is true, because the last log that i cannot explain is very odd (https://classic.warcraftlogs.com/reports/d8tCHzav2RhkFVNP#fight=58)...if there is not a bug:(
In this log, Ouro "should" keep attacking the maintank but it submerges.
Ouro keeps melee at the maintank named "Cairune" before it casts sand blast to an overthreat ranged player. So the maintank does not influenced by the sand blast and keeps his threat. His last melee against Ouro happens at 01:31.884. Ouro casts submerge at 01:33.902, this 2-second gap seems too short... and the replay shows that the tank does not move during this gap...

However, this is the only log that I find cannot explained by my guess... maybe we should wait for more logs to find out what is the condition 2. But the condition 1 should be true, if we cannot find a log that ouro keeps on the ground more than 3min before its HP is lower that 20%.

**Comment by ResultsMayVary** [comment]
In that log a sand blast hits the raid (26 members). Have to imagine that's related. Otherwise I came here to make the exact same issue. Submerge happens under 2 conditions.

1. Nobody is in melee range
2. 3 minutes have passed since engage/birth.

You can have a "Forced submerge" timer which is 3 minutes.

**Comment by MysticalOS** [comment]
I like "forced submerge"
I put in submerge (max) but that makes more sense

**Comment by ResultsMayVary** [comment]
One additional comment, Ouro will no longer submerge once he berserks. I checked the code and didn't see you stopping the timer when that happens. Unless that is handled automatically. Not familiar with the codebase.

**Comment by MysticalOS** [comment]
Oh right I have to add a stop call there. I prevent timer from starting if berserked but not cancel it.

**Comment by MysticalOS** [comment]
Closing this, as I think it's good in current code.
