### ISSUE TITLE
AQ40 Twin Emps - Exploding Bug change

### ISSUE THREAD

**Issue by jmibo** [DeadlyBossMods/DBM-Classic#473]
Regarding AQ40 Twin emps mod, its probably better to alert people about exploding bugs by default.

I had a look at alerting the raid with a weakaura before i found the option in dbm just disabled.

**Comment by MysticalOS** [comment]
I recall disabling that because it felt spammy sometimes. those things can go explodey with almost no CD sometimes. I wish there was a better way to educate people about options though without having to make things on by default. I'll check WCL later to see how spammy it feels on classic and enable it though if it's not too bad. It was bad when i made mods but that was during TBC or wrath so the scripting may not be same in classic.

**Comment by jmibo** [comment]
Yeah i was wondering just how spammy it would be. Its a shame we cant narrow the alerts down to a bug nearby anymore.

For reference, we had 22 explosions over a 5m 20s fight last week.

**Comment by MysticalOS** [comment]
if they hadn't disabled UNIT_SPELLCAST events for non player units, I could have only warned if a bug in nameplate range exploded, but classic is classic and they restricted that.
