### ISSUE TITLE
Lua error on logon after 8.3.8 update (2020-01-29)

### ISSUE THREAD

**Issue by cdobbyn** [DeadlyBossMods/DBM-Classic#51]
**Describe the bug**
After updating to 8.3.8 DBM no longer loads properly, and if an error capture tool like swatter is present it displays the following error (see error log below). If I type /dbm, the output is `<DBM> nil`.

**Do you have an error log of what happened?**
```
Date: 2020-01-31 20:26:03
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\DBM-Core\localization.en.lua line 3:
   attempt to call field 'GetCurrentCalendarTime' (a nil value)
Debug:
   DBM-Core\localization.en.lua:3: in main chunk
Locals:
(*temporary) = nil
(*temporary) = "attempt to call field 'GetCurrentCalendarTime' (a nil value)"

AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  DBMCore, v8.3.8
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=92)
```

**To Reproduce**
Log on, immediately see the error.

**Screenshots**
![image](https://user-images.githubusercontent.com/8264498/73586841-e30fb880-4467-11ea-9a81-15493269f9a8.png)
![image](https://user-images.githubusercontent.com/8264498/73586853-0fc3d000-4468-11ea-95ac-f6d14141ac95.png)

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
All mods were disabled except for DBM and Swatter, saved variables were cleaned.

**Which version of DeadlyBossMods are you using?**
8.3.8

**Was it working in a previous version? If yes, which was the last good one?**
Yes, 8.3.7.

**Additional context**
This appears isolated to the core or required libraries.

I install/manage the DBM addon via the twitch client.

**Comment by MysticalOS** [comment]
That should not be used on classic, at all. that's for retailonly. DBM classic should be using 1.13.30

**Comment by cdobbyn** [comment]
DBM classic is not published on the twich client anymore I guess.

**Comment by cdobbyn** [comment]
@MysticalOS Who publishes this to the twitch client? Looks like that's the problem, it's installing the wrong version.

**Comment by cdobbyn** [comment]
Looks like someone fixed. Thanks for all you do!

**Comment by MysticalOS** [comment]
twitch client sometimes mixes up game versions, no one knows why, but the correct files are in correct place, the client just flips them sometimes and only for some users. I use twitch client DAILY to update retail and classi addons and have only seen the wrong addon issue when it's globally flipped (only happend twice). for the single users here and there that get it, no one knows why other than it's on twitches end and bug reports need to be filed with them to keep pressuring them to investigate issue because it's a huge issue for users and mod authors. :\

to solve your current issue, remove your dbm folders from your install and download the CLASSIC version
