### ISSUE TITLE
Loatheb Doom timer should be more accurate.

### ISSUE THREAD

**Issue by gwtwind** [DeadlyBossMods/DBM-Classic#713]
**Describe the bug**
Loatheb Doom timer is something inaccurate now.
So rogues are difficult to use Vanish to evade Doom.

First Doom is 121.4-121.5 sec
2nd 29.1
3rd 32.4
4th 29.1
5th 32.4
until 7th Doom

**Which version of DeadlyBossMods are you using?**
1.13.70-classic

**Pull Request**
Loatheb.lua

Line 78: 
`timerDoom:Start(121.4 - delay, self.vb.doomCounter + 1)`

Line 113:
```
local timer
if self.vb.doomCounter % 2 == 1 then timer = 29.1
else timer = 32.4 end
```

**Comment by MysticalOS** [comment]
What happens after 7th one?

**Comment by gwtwind** [comment]
Loatheb use doom more frequently
8th 9.6-9.8
9th 19.4-19.5
10th 11.3-11.4
11th No one can not alive now

**Comment by gwtwind** [comment]
> What happens after 7th one?
Loatheb use doom more frequently
8th 9.6-9.8
9th 19.4-19.5
10th 11.3-11.4
11th 19.4-19.5 (No one can not alive now, commonly)
12th 11.3-11.4
13th No log

**Comment by venuatu** [comment]
yep I'm seeing that too, these numbers are from 160 loathebs, most came from 330+ second fights on warcraftlogs
seems like most of them go off with the max variation of 0.13 seconds
doom 11 had some more variation, but there was one at 19.38. so I'd go with that rather than adding a different 20.6 interval in there

these are the intervals I'd go with:
```
2   29.09
3   32.31
4   29.09
5   32.31
6   29.09
7   32.31
8   9.68
9   19.38
10  11.3
11  19.38
12  9.68
13  19.38
```
more data is in: https://gist.github.com/venuatu/66e09bacbd45ca33b9e164ff5bd46949

and if your curious the 13 doom one was: https://classic.warcraftlogs.com/reports/RXktxrLfnz1GyYWB#translate=true&fight=last&type=casts&view=events&hostility=1&ability=29204
that's pretty crazy to me, as my guild usually kills this with 3 or 4 dooms

**Comment by gwtwind** [comment]
> 8   9.68

Caution: 8th doom is ignored, no damage on player. But addon should recognize it.

**Comment by venuatu** [comment]
whoa, that seems broken
the doom debuff does the damage at 10 seconds, so if a doom goes out before that (8 & 12) it doesn't refresh the debuff and is ignored
so the damage alternates between 29.09 and 32.31 and then starting on doom 10 it goes to 11.3, 21.01, 29.09 (the 32.31 doom splits into the 11.3 and 21.01 ones)

**Comment by gwtwind** [comment]
I agree
