### ISSUE TITLE
Chat Tab Overflow List not Glowing (with ElvUI) due to LibChatAnims.lua used by DBM Core

### ISSUE THREAD

**Issue by JaimzWoW** [DeadlyBossMods/DBM-Classic#763]
**Describe the bug**
Chat Tab Overflow List not Glowing (with ElvUI) due to `LibChatAnims.lua` (https://github.com/DeadlyBossMods/DBM-TBC-Classic/blob/master/.pkgmeta) that's being used by DBM Core. I reached out to DBM's Discord to double check why DBM uses this lib and it turns out that it may be a leftover from years ago (for an old DBM version). This lib contains a `FCF_StartAlertFlash()` and `FCF_StopAlertFlash()` method that I commented out to confirm that DBM does work without it (which is the case), I also added some output prints to ensure it's not using the lib. Therefore, I would like to request if this can be removed from the DBM Core.

**Do you have an error log of what happened?**
- 'Disabled' `LibChatAnims.lua`
- Typed `/console scriptErrors 1`
- Enabled only ElvUI & DBM Core
- Performed like 6-7 DBM test runs via Core & GUI (tried it once during combat)
- The DBM bars, sounds and chat announcements work as expected
- No LUA errors appeared

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Everything was disabled but ElvUI (v2.23) and DBM Core (v2.5.19).

**Which version of DeadlyBossMods are you using?**
v2.5.19

**Was it working in a previous version? If yes, which was the last good one?**
N/A

**Additional context**

**Comment by QartemisT** [comment]
So, the reason we use this library is because it helps prevent "taint" issues within WoW for when we add chat messages and the likes.
Basically, whenever a 3rd party addon starts touching and messing with the ChatFrame code (blame most chat addons for this), it is modifying globals and how WoW handles certain calls. In turn, if this starts bugging when we attempt to make a call to add a message to the chat, it will throw an error blaming DBM, which obviously, isn't the case.

Your best recommendation is if something is acting weird, is to report it to funkehdude (who maintains LibChatAnims), or ask ElvUI for better support with it.
